Message.create(content: "Hello, World!")
Message.create(content: "Greetings from Rails!")
Message.create(content: "Welcome to the API!")
Message.create(content: "Hi there!")
Message.create(content: "Howdy!")
